# permissions for end users to edit generators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generator-editor-role
rules:
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators/status
  verbs:
  - get
