
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.argoproj.io
  resources:
  - generators/status
  verbs:
  - get
  - patch
  - update
